// `verify` — deterministic checks over what the agent (or the fallback)
// proposed, before anything is persisted or shown to anyone.
//
// Two checks, both load-bearing:
//
//   HARD FILTER   a plan a coverage gap rules out is stripped from the
//                 shortlist regardless of what proposed it.
//                 `propose_shortlist` (lib/ai/tools/plans.ts) already does
//                 this once, mid-loop; re-running it here catches drift and
//                 covers the deterministic fallback path too.
//
//   CITATION CHECK  every number in the two reasoning registers must trace
//                 back to an observation the trace actually recorded (doc
//                 §4.3) — a figure with no matching observation is a
//                 hallucination, not a rounding difference. The fallback's
//                 prose is exempt: it is templated straight from the same
//                 arithmetic that ranked the plans, not generated by a model
//                 with room to invent.
//
// Either failure drops confidence to `low`, which is what sends
// `recommendationGate` (the next node) to an advisor instead of the applicant.

import "server-only";
import { isEligible } from "@/lib/recommendation";
import type { RecommendationStateType } from "@/lib/ai/graph/state";

/** Every currency figure or waiting-period month worth citing, pulled out of prose. */
function numbersIn(text: string): string[] {
  return [...text.matchAll(/\d[\d,]*(?:\.\d+)?/g)].map((m) => m[0].replace(/,/g, ""));
}

export function verify(state: RecommendationStateType): Partial<RecommendationStateType> {
  const validShortlist = state.shortlist.filter((pick) => {
    const plan = state.catalogue.plans.find((p) => p.id === pick.planId);
    return plan != null && isEligible(plan, state.record);
  });
  const stripped = state.shortlist.filter((pick) => !validShortlist.some((v) => v.planId === pick.planId));

  let uncited: string[] = [];
  if (state.fellBackTo == null) {
    const observed = new Set(state.trace.flatMap((step) => (step.validation === "ok" ? numbersIn(step.observationSummary) : [])));
    const cited = numbersIn(`${state.brokerReasoning ?? ""} ${state.memberReasoning ?? ""}`);
    uncited = cited.filter((n) => !observed.has(n));
  }

  const verifyFailed = stripped.length > 0 || uncited.length > 0 || validShortlist.length === 0;

  return {
    shortlist: validShortlist.length > 0 ? validShortlist : state.shortlist,
    rejections:
      stripped.length > 0
        ? [
            ...state.rejections,
            ...stripped.map((s) => ({ planId: s.planId, reason: "Stripped at verification — does not cover a declared need." })),
          ]
        : state.rejections,
    verifyFailed,
    recoConfidence: verifyFailed ? "low" : state.recoConfidence,
    recoUncertaintyReason: verifyFailed
      ? uncited.length > 0
        ? `A figure in the reasoning (${uncited.join(", ")}) does not trace back to a tool observation.`
        : "One or more shortlisted plans failed the eligibility check at verification."
      : state.recoUncertaintyReason,
  };
}
